import CategorySection from "@/components/ui/CategorySection";
import Footer from "@/components/ui/FooterSection";
import HeroSection from "@/components/ui/HeroSection";
import RecommendationSection from "@/components/ui/RecommendationSection";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Basic Next.js App",
  description: "Generated by create next app",
  authors: [{ name: "Beel", url: "https://beellionaire.com" }],
  icons: {
    icon: "/n.png",
  },
};

export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-between">
      <div className="min-h-screen w-full bg-slate-200 dark:bg-slate-800">
        {/* Hero Section */}
        <HeroSection />
        <CategorySection />
        <RecommendationSection />
        <Footer />
      </div>
    </main>
  );
}
